version: "3.8"
services:
  store-backend:
    image: store-backend:latest
    container_name: store-backend
    profiles:
      - full
    restart: always
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    profiles:
      - full
      - dev
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - backend/.env

  test-postgres:
    container_name: test-postgres
    image: postgres:14.1-alpine
    profiles:
      - test
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    env_file:
      - backend/testconfig_example.env

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-01-02T09-40-09Z.fips
    profiles:
      - full
      - test
      - dev
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    env_file:
      - backend/.env
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
    name: postgres-data
  test-postgres-data:
    name: test-postgres-data
  minio-storage:
    name: minio-storage