version: "3.8"
services:
  api:
    container_name: shop-api
    restart: always
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
    name: postgres-data