version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  api:
    container_name: shop-backend-api
    build:
      context: ./
    ports:
      - "5000:5000"
volumes:
  db:
    driver: local
