version: "3.8"
services:
  api:
    container_name: shop-api
    restart: always
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-01-02T09-40-09Z.fips
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${PRODUCTS_BUCKET};
      /usr/bin/mc policy set public myminio/${PRODUCTS_BUCKET};
      exit 0;
      "

volumes:
  postgres-data:
    name: postgres-data
  minio-storage:
    name: minio-storage