"""empty message

Revision ID: 9bde61e3827d
Revises: 165811bed174
Create Date: 2023-05-21 00:04:19.237348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bde61e3827d'
down_revision = '165811bed174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('preview_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_images', ['preview_image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'preview_image_id')
    # ### end Alembic commands ###
